//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entregables
    {
        public int Id { get; set; }
        public int TareaId { get; set; }
        public int EstudianteId { get; set; }
        public string NombreDocumento { get; set; }
        public string Extension { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual Tareas Tareas { get; set; }
    }
}
